### ISSUE TITLE
poem&code

### ISSUE THREAD

**Issue by EXfeiniao** [KroMiose/nonebot_plugin_naturel_gpt#1]
似乎不能把诗歌和代码等长内容发送出来，诗歌在控制台可以看到，代码在控制台看不见

**Comment by KroMiose** [comment]
目前的程序没有对生成内容的长度进行过额外处理，可以尝试修改token限制，或者查看适配器方面（如gocqhttp）有没有更具体的错误信息

**Comment by KroMiose** [comment]
@EXfeiniao 该问题已确认，原因是早期开发测试时把双回车符设为了停用词，导致代码等长内容输出过程碰到双回车被自动打断了，最新版本已修复 ◑﹏◐
