### ISSUE TITLE
bot回复内容重复

### ISSUE THREAD

**Issue by webjoin111** [KroMiose/nonebot_plugin_naturel_gpt#10]
bot在新的回复中，经常会在结尾重复补上很久前已经回复过的内容，跟近期的聊天内容毫不相干，导致聊天时很出戏。
触发机制不清楚，有的群员会触发，有的不会。

**Comment by KroMiose** [comment]
bot的聊天回应一直是比较难以掌控的，这可能和你的群聊内容是否具有“可回复性”相关，也可能与你的人格预设设计有关

以下是针对上述场景的猜测情况：
bot在回复时会参考对触发者的历史印象（由bot与该成员的聊天记录总结产生），如果上文信息比较难以回复，bot会根据记录的印象认为你对某个话题感兴趣，从而更倾向于“转移话题”到该话题上，以此来引导聊天方向

您可以尝试修改配置文件中的 频率惩罚、重复惩罚、温度 几项参数（具体如何调节值可以参考openai的官方文档说明），来提高一些bot回复的灵活性和随机性
