### ISSUE TITLE
解除限制好像没用

### ISSUE THREAD

**Issue by Yunmo-1** [KroMiose/nonebot_plugin_naturel_gpt#113]
![image](https://user-images.githubusercontent.com/79674967/229124372-18a16e2b-c88c-49d8-8b1c-f57febcd78de.png)
是bug吗？

**Comment by Yunmo-1** [comment]
怎么才能色色啊

**Comment by KroMiose** [comment]
这个原因比较玄学，可以尝试更换一个api key或者openai账号，另外也可能和人设有关，可以从云文档中获取一些参考

**Comment by Yunmo-1** [comment]
确实比较玄，最近又可以涩涩了
