### ISSUE TITLE
如何能够稳定调用扩展插件？

### ISSUE THREAD

**Issue by Fatima-meow** [KroMiose/nonebot_plugin_naturel_gpt#117]
我参考voice插件写了调用azureTTS的语音扩展，但是bot调用语音插件似乎不是很积极，得反复强调才会调用一次

**Comment by KroMiose** [comment]
首先要确保扩展的描述达意准确，其次人格本身也有影响，可以通过在人格中写上喜欢以语音形式发送消息等方式来控制

**Comment by Fatima-meow** [comment]
> 首先要确保扩展的描述达意准确，其次人格本身也有影响，可以通过在人格中写上喜欢以语音形式发送消息等方式来控制

如果我想要实现用语音取代所有回复的文本，是不是应该更改macher.py，求大佬指点一下，工科非计算机系小白，学了好几天python没看懂

**Comment by KroMiose** [comment]
建议使用人格控制的方式，因为bot的回复多种多样，有时候会产生长内容的代码回复，源代码中如果要强制使用语音进行回复会对现有框架造成严重破坏，尝试在人格设定中加上“ta在产生回复时只会使用语音回复消息，永远不会产生语音内容以外的任何文字回复”，这样产生的影响较小，而且不会与其它扩展造成冲突

**Comment by Fatima-meow** [comment]
> 建议使用人格控制的方式，因为bot的回复多种多样，有时候会产生长内容的代码回复，源代码中如果要强制使用语音进行回复会对现有框架造成严重破坏，尝试在人格设定中加上“ta在产生回复时只会使用语音回复消息，永远不会产生语音内容以外的任何文字回复”，这样产生的影响较小，而且不会与其它扩展造成冲突

我试过这种方法，但是bot会认为自己在角色扮演不会调用扩展，除非我反复提醒

**Comment by KroMiose** [comment]
如果你要强制性对所有回复都调用语音扩展，最简单的方案是在bot产生的原始回应之后，执行扩展之前（https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/16dfd03fdd977ca6452483d6dbe72f59e32e3df9/nonebot_plugin_naturel_gpt/matcher.py#L333）直接使用 /#voice&{raw_response}#/ 包括，这样后续的解析流程就会把所有的响应当作语音内容处理，但是同时也无法加载其它任何扩展，因为扩展不支持嵌套执行，另外在此情况下如果bot产生了诸如代码文本等长内容可能出现难以预料的结果
仅供参考的方案，不推荐长期使用

**Comment by Fatima-meow** [comment]
> 

谢谢大佬，我测试了一下，在`    # 提取markdown格式的代码块
    code_blocks = re.findall(r"```(.+?)```", raw_res, re.S)`
这一行前面加上    raw_res += f"/#voice&{raw_res}#/"
这样就实现了我想要的效果，不过目前使用来看不是特别稳定，bot容易狂暴回复一次好几条
