### ISSUE TITLE
语音插件发送语音是代码

### ISSUE THREAD

**Issue by Arturia169** [KroMiose/nonebot_plugin_naturel_gpt#120]
如图
![image](https://user-images.githubusercontent.com/69199123/230396572-dc400878-c4a5-4c4d-905b-0653bbdd2793.png)
控制台如图
![image](https://user-images.githubusercontent.com/69199123/230396680-ebfe9887-a3e3-4b3e-a4e4-5e2b9b7e73bc.png)

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/230396063-84b45a59-f1da-4ce3-bb89-60510cdcdf32.png)
如图
控制台如图
![image](https://user-images.githubusercontent.com/69199123/230396303-c0230ce7-5e00-477a-ae3f-9e28e25949a5.png)

**Comment by KroMiose** [comment]
该问题出现在gocq端，请参考其它issue或者尝试更换gocq为较老的版本
