### ISSUE TITLE
无法加载机器人

### ISSUE THREAD

**Issue by pshta0** [KroMiose/nonebot_plugin_naturel_gpt#121]
如图，一加载就报错。
![image](https://user-images.githubusercontent.com/122964169/230737388-c502f0f7-4696-41de-924b-790e5a90f07b.png)

python版本：3.8.10_32bits. 
Windows10
安装的几个包：
nb-cli                     1.0.5
nonebot-adapter-onebot     2.2.1
nonebot-plugin-gocqhttp    0.6.7
nonebot-plugin-gpt3        1.1.3
nonebot-plugin-htmlrender  0.2.0.3
nonebot-plugin-naturel-gpt 2.0.5
nonebot2                   2.0.0rc3
openai                     0.27.0

操作步骤：
1、打开go_cqhttp，建立连接
2、在项目文件夹nb run --reload

**Comment by KroMiose** [comment]
不要使用 --reload 启动，插件加载时读写目录文件时会导致nb自动重载，导致无限重启

**Comment by pshta0** [comment]
> 不要使用 --reload 启动，插件加载时读写目录文件时会导致nb自动重载，导致无限重启

你好，使用nb run 或者nb 在当前文件夹运行机器人也是同样报错。我不清楚是什么原因，也许不是本插件的原因

**Comment by KroMiose** [comment]
可以尝试重装nb或者更换运行环境，如有更具体的报错信息可提供参考

**Comment by pshta0** [comment]
> 可以尝试重装nb或者更换运行环境，如有更具体的报错信息可提供参考

更具体的信息是指？因为我这边一旦加载了机器人，它就python.exe发生了异常，如图所示，关闭调试就自己结束了，没有其他打印的信息。重新安装也是一样的结果，如果不加载本插件的确可以正常startup

**Comment by KroMiose** [comment]
这很可能是你本身的环境存在问题，nonebot在加载插件时发生错误应该会给出错误信息，然后跳过这个插件的加载，而不会整个python完全崩溃，可能需要完全重装python和nonebot才能解决，至于正常的报错信息会如何呈现你可以参考其他issue看看

**Comment by pshta0** [comment]
> 这很可能是你本身的环境存在问题，nonebot在加载插件时发生错误应该会给出错误信息，然后跳过这个插件的加载，而不会整个python完全崩溃，可能需要完全重装python和nonebot才能解决，至于正常的报错信息会如何呈现你可以参考其他issue看看
> 
> 另外，建议尝试更换64位的python版本，32位版本也可能会导致意外问题

好的。我晚点试试

**Comment by pshta0** [comment]
> 这很可能是你本身的环境存在问题，nonebot在加载插件时发生错误应该会给出错误信息，然后跳过这个插件的加载，而不会整个python完全崩溃，可能需要完全重装python和nonebot才能解决，至于正常的报错信息会如何呈现你可以参考其他issue看看
> 
> 另外，建议尝试更换64位的python版本，32位版本也可能会导致意外问题

使用了python3.11.3_64bits，没再报错
