### ISSUE TITLE
人格重置后第一次对话似乎有问题？

### ISSUE THREAD

**Issue by OverSky-gtq** [KroMiose/nonebot_plugin_naturel_gpt#122]
![QQ图片20230409134206](https://user-images.githubusercontent.com/101913851/230756533-c3eba698-813c-401d-b24a-5614f5e644e4.jpg)

**Comment by KroMiose** [comment]
重置指令应为 rg reset （在你的场景中应该是 /rg reset ），指令在重构更新后已不再支持旧版的指令中文别名

**Comment by OverSky-gtq** [comment]
搜嘎，原来如此
