### ISSUE TITLE
合作项目

### ISSUE THREAD

**Issue by jsuguo** [KroMiose/nonebot_plugin_naturel_gpt#13]
开发一个聊天工具，可以先开一个合适的价格。Email：8598239@qq.com 电话13615899736

**Comment by KroMiose** [comment]
不好意思哈，由于最近此类项目比较多，我对这类项目是否具有可行性和开发价值暂时存疑，如果您的项目有清晰的规划，请提交项目书或相关文档到邮箱kromiose@163.com
