### ISSUE TITLE
让bot编写一篇实习日志说发邮箱了然而并没收到

### ISSUE THREAD

**Issue by XiaoLong2333** [KroMiose/nonebot_plugin_naturel_gpt#134]
![`TLHT01$BE`2S(SL@I{QI{J](https://user-images.githubusercontent.com/42651551/233833945-5e573653-2160-4ba0-a3bd-bb9543a095a1.jpg)

**Comment by XiaoLong2333** [comment]
为啥不能在对话里就写好呢，我看到邮件地址也没有填入邮箱地址什么的，今天首次装入此插件遇到的，也不怎么会玩，求开发看看问题

**Comment by KroMiose** [comment]
尝试reset或者直接告诉她邮件功能无法使用，要求她在聊天中直接发送出来，gpt自动脑补不存在的信息是老毛病了，如果她这么做了需要直接予以纠正，让她意识到自己的行为有问题，或者直接在人格中规范她的行为
