### ISSUE TITLE
对话已被禁用，跳过处理...

### ISSUE THREAD

**Issue by sun0225SUN** [KroMiose/nonebot_plugin_naturel_gpt#14]
![image](https://user-images.githubusercontent.com/79169717/219838675-ca684706-935e-452c-86c9-ecb00c50fbc5.png)

我啥也没改，这个咋回事，咋恢复会话哇！

**Comment by sun0225SUN** [comment]
这边删除了之前存储的数据，就可以正常对话了。。。

**Comment by KroMiose** [comment]
@sun0225SUN 尝试使用 `rg on` 指令手动开启会话看是否正常
