### ISSUE TITLE
paint 绘图扩展使用出错：未找到扩展 image，跳过调用...

### ISSUE THREAD

**Issue by xiaowww3** [KroMiose/nonebot_plugin_naturel_gpt#140]
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/84241722/3af779f3-8250-4c8e-a70e-97738a5b5445)

**Comment by KroMiose** [comment]
请确认扩展是否正确加载（rg ext），尝试reset上下文

**Comment by xiaowww3** [comment]
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/84241722/ba283e2d-7161-4d78-b123-34220bc44bc8)

**Comment by KroMiose** [comment]
不要开启nonebot的自动重载（--reload）否则在检测到目录文件有变化就会重启
