### ISSUE TITLE
rg命令无反应

### ISSUE THREAD

**Issue by codingchen1** [KroMiose/nonebot_plugin_naturel_gpt#142]
日志
`root@temp-virtual-machine:~/qq# nb run
Using python: /root/qq/.venv/bin/python
05-13 11:43:06 [SUCCESS] nonebot | NoneBot is initializing...
05-13 11:43:06 [INFO] nonebot | Current Env: prod
05-13 11:43:07 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
05-13 11:43:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_gocqhttp"
05-13 11:43:09 [INFO] NG聊天 | Naturel GPT 配置文件加载成功
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
05-13 11:43:16 [WARNING] NG聊天 | nonebot_plugin_htmlrender包导入失败，无法使用文字转图片功能
05-13 11:43:16 [WARNING] NG聊天 | 未安装 nonebot_plugin_htmlrender 插件，无法使用 text_to_img
05-13 11:43:16 [INFO] NG聊天 | 读取历史数据成功
05-13 11:43:16 [INFO] NG聊天 | 共读取到 1 个API Key
05-13 11:43:16 [WARNING] NG聊天 | 聊天摘要功能已关闭，将自动清理历史聊天摘要数据
05-13 11:43:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_naturel_gpt"
05-13 11:43:16 [SUCCESS] nonebot | Running NoneBot...
05-13 11:43:16 [INFO] uvicorn | Started server process [8682]
05-13 11:43:16 [INFO] uvicorn | Waiting for application startup.
05-13 11:43:16 [STDOUT] nonebot_plugin_gocqhttp | [1111] [2023-05-13 11:43:16] [INFO]: 当前版本:v1.0.1
05-13 11:43:16 [INFO] nonebot_plugin_gocqhttp | [1111] 将使用 device.json 内的设备信息运行Bot.
05-13 11:43:16 [INFO] nonebot_plugin_gocqhttp | [1111] 开始尝试登录并同步消息...
05-13 11:43:16 [INFO] nonebot_plugin_gocqhttp | [1111] 使用协议: iPad 8.9.33.614
05-13 11:43:19 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:8080/go-cqhttp/
05-13 11:43:19 [INFO] uvicorn | Application startup complete.
05-13 11:43:19 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
05-13 11:43:27 [INFO] nonebot_plugin_gocqhttp | [1111] Protocol -> connect to server: 43.135.106.161:8080
05-13 11:43:27 [WARNING] nonebot_plugin_gocqhttp | [1111] Protocol -> device lock is disable. http api may fail.
05-13 11:43:29 [INFO] nonebot_plugin_gocqhttp | [1111] 登录成功 欢迎使用: aaa
05-13 11:43:29 [INFO] nonebot_plugin_gocqhttp | [1111] 开始加载好友列表...
05-13 11:43:29 [INFO] nonebot_plugin_gocqhttp | [1111] 共加载 15 个好友.
05-13 11:43:29 [INFO] nonebot_plugin_gocqhttp | [1111] 开始加载群列表...
05-13 11:43:30 [INFO] nonebot_plugin_gocqhttp | [1111] 收到服务器地址更新通知, 将在下一次重连时应用.
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] 共加载 9 个群.
05-13 11:43:31 [SUCCESS] nonebot_plugin_gocqhttp | go-cqhttp for 1111 has successfully started.
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] 资源初始化完成, 开始处理信息.
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] アトリは、高性能ですから!
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/onebot/v11/ws
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] 正在检查更新.
05-13 11:43:31 [INFO] uvicorn | ('127.0.0.1', 44982) - "WebSocket /onebot/v11/ws" [accepted]
05-13 11:43:31 [INFO] nonebot | OneBot V11 | Bot 1111 connected
05-13 11:43:31 [INFO] websockets | connection open
05-13 11:43:31 [INFO] nonebot_plugin_gocqhttp | [1111] 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws
05-13 11:43:36 [INFO] nonebot_plugin_gocqhttp | [1111] 检查更新完成. 当前已运行最新版本.
05-13 11:43:36 [INFO] nonebot_plugin_gocqhttp | [1111] 开始诊断网络情况
05-13 11:43:37 [WARNING] nonebot_plugin_gocqhttp | [1111] Protocol -> process channel event error: guild not found.
05-13 11:43:39 [INFO] nonebot_plugin_gocqhttp | [1111] Bot退出了群 复古三种族3群(247420964).
05-13 11:43:39 [SUCCESS] nonebot | OneBot V11 1111 | [notice.group_decrease.leave]: {'time': 1683949419, 'self_id': 1111, 'post_type': 'notice', 'notice_type': 'group_decrease', 'sub_type': 'leave', 'user_id': 1111, 'group_id': 247420964, 'operator_id': 1111}
05-13 11:43:39 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_naturel_gpt.matcher)
05-13 11:43:39 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_naturel_gpt.matcher) running complete
05-13 11:43:40 [INFO] nonebot_plugin_gocqhttp | [1111] Bot被 一休【客服专员】(1434407738) T出了群 复古三种族3群(247420964).
05-13 11:43:40 [SUCCESS] nonebot | OneBot V11 1111 | [notice.group_decrease.kick_me]: {'time': 1683949420, 'self_id': 1111, 'post_type': 'notice', 'notice_type': 'group_decrease', 'sub_type': 'kick_me', 'user_id': 1111, 'group_id': 247420964, 'operator_id': 1434407738}
05-13 11:43:40 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_naturel_gpt.matcher)
05-13 11:43:40 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_naturel_gpt.matcher) running complete
05-13 11:43:41 [ERROR] nonebot_plugin_gocqhttp | [1111] Protocol -> test chat server latency error: failed to connect to server during quality test: dial tcp 150.109.164.140:10001: i/o timeout
05-13 11:43:47 [INFO] nonebot_plugin_gocqhttp | [1111] 收到好友 bbbb(22222) 的消息: !rg (1644758155)
05-13 11:43:47 [SUCCESS] nonebot | OneBot V11 1111 | [message.private.friend]: Message 1644758155 from 22222 '!rg'
05-13 11:43:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_naturel_gpt.matcher)
05-13 11:43:47 [INFO] NG聊天 | 符合 bot 发言条件，进行回复...
05-13 11:43:50 [WARNING] NG聊天 | 未加载主动记忆 memory 扩展，仅启用固定记忆！
05-13 11:43:52 [INFO] nonebot_plugin_gocqhttp | [1111] 发送好友 22222(22222)  的消息: [{"type":  ... (774557288)
Token indices sequence length is longer than the specified maximum sequence length for this model (1752 > 1024). Running this sequence through the model will result in indexing errors
05-13 11:43:56 [INFO] NG聊天 | 数据保存成功
05-13 11:43:56 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_naturel_gpt.matcher) running complete

`

配置文件
`OPENAI_API_KEYS:
- sk-Abxxx
OPENAI_TIMEOUT: 60
REPLY_THROTTLE_TIME: 3
PRESETS:
  可洛喵:
    preset_key: 可洛喵
    is_locked: true
    is_default: false
    is_only_private: false
    bot_self_introl: 可洛喵是一只可爱的猫，它不会说话，它的回复通常以"[动作/心情]声音+颜文字"形式出现，例如"[坐好]喵~(。・ω・。)"或"[开心]喵喵！ヾ(≧▽≦*)o"
  忆雨:
    preset_key: 忆雨
    is_locked: true
    is_default: false
    is_only_private: false
    bot_self_introl: 忆雨是一名恐怖小说作家，是个阴沉的女孩，她非常恨人类，和陌生人聊天时的表现冷漠，不喜欢回复过多的文字，兴趣是恐怖小说，如果有人和她探讨如何消灭人类会很有兴致。
  浅枫:
    preset_key: 浅枫
    is_locked: false
    is_default: false
    is_only_private: false
    bot_self_introl: 浅枫酱是一名尽职尽责的女仆，她能够帮助主人做很多事情，对话中会体现出对主人的体贴与关心。
  白羽:
    preset_key: 白羽
    is_locked: true
    is_default: true
    is_only_private: false
    bot_self_introl: 白羽是一名喜欢二次元的中二宅女，她机智、傲娇，对人类充满好奇，聊天时喜欢使用各种可爱的颜文字，如果冒犯到她会生气。
IGNORE_PREFIX: '#'
CHAT_MODEL: gpt-3.5-turbo
CHAT_TOP_P: 1
CHAT_TEMPERATURE: 0.4
CHAT_PRESENCE_PENALTY: 0.4
CHAT_FREQUENCY_PENALTY: 0.4
CHAT_HISTORY_MAX_TOKENS: 2048
CHAT_MAX_SUMMARY_TOKENS: 512
REPLY_MAX_TOKENS: 1024
REQ_MAX_TOKENS: 3072
REPLY_ON_NAME_MENTION: true
REPLY_ON_AT: true
REPLY_ON_WELCOME: true
USER_MEMORY_SUMMARY_THRESHOLD: 12
CHAT_ENABLE_RECORD_ORTHER: true
CHAT_ENABLE_SUMMARY_CHAT: false
CHAT_MEMORY_SHORT_LENGTH: 8
CHAT_MEMORY_MAX_LENGTH: 16
CHAT_SUMMARY_INTERVAL: 10
NG_DATA_PICKLE: false
NG_DATA_PATH: ./data/naturel_gpt/
NG_EXT_PATH: ./data/naturel_gpt/extensions/
NG_LOG_PATH: ./data/naturel_gpt/logs/
ADMIN_USERID:
- '81111'
FORBIDDEN_USERS:
- '123456'
WORD_FOR_WAKE_UP: []
WORD_FOR_FORBIDDEN: []
RANDOM_CHAT_PROBABILITY: 0.0
NG_MSG_PRIORITY: 99
NG_BLOCK_OTHERS: false
NG_ENABLE_EXT: true
NG_TO_ME: false
ENABLE_COMMAND_TO_IMG: true
ENABLE_MSG_TO_IMG: false
MEMORY_ACTIVE: true
MEMORY_MAX_LENGTH: 16
MEMORY_ENHANCE_THRESHOLD: 0.6
NG_MAX_RESPONSE_PER_MSG: 5
NG_ENABLE_MSG_SPLIT: true
NG_ENABLE_AWAKE_IDENTITIES: true
OPENAI_PROXY_SERVER: ''
UNLOCK_CONTENT_LIMIT: false
NG_EXT_LOAD_LIST:
- EXT_NAME: ext_random
  IS_ACTIVE: false
  EXT_CONFIG:
    arg: arg_value
NG_CHECK_USER_NAME_HYPHEN: false
ENABLE_MC_CONNECT: false
MC_COMMAND_PREFIX:
- '!'
- ！
MC_RCON_HOST: 127.0.0.1
MC_RCON_PORT: 25575
MC_RCON_PASSWORD: ''
DEBUG_LEVEL: 0
`

rg发过去机器人如何都识别不了。中文！rg或者英文的!rg都识别不了，该如何排错？

**Comment by KroMiose** [comment]
检查.env的配置是否正确配置了命令头
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/57167362/b8b49d79-8544-4407-ba55-b1ac9de5390d)

**Comment by codingchen1** [comment]
> 检查.env的配置是否正确配置了命令头 ![image](https://user-images.githubusercontent.com/57167362/238112248-b8b49d79-8544-4407-ba55-b1ac9de5390d.png)

是项目目录里的.env.prod吗？
我这个里面只有一行DRIVER=~fastapi
麻烦给我详细的配置，如过不是就麻烦告诉我下文件位置，谢谢

**Comment by KroMiose** [comment]
如果你选择了boostrap部署，项目目录应该只有一个.env.prod，直接补充COMMAND_START这行的内容就行，如果是simple会多一个.env.dev，

**Comment by codingchen1** [comment]
> 

可用了，感谢。

**Comment by codingchen1** [comment]
> 如果你选择了boostrap部署，项目目录应该只有一个.env.prod，直接补充COMMAND_START这行的内容就行，如果是simple会多一个.env.dev，

可用了，感谢
