### ISSUE TITLE
建议添加代理设置，比如允许使用反向代理

### ISSUE THREAD

**Issue by sfvsfv** [KroMiose/nonebot_plugin_naturel_gpt#144]
查看源码部分发现是直接调用的openai模块，国内服务器无法直接访问。需要单独配置VPN，感觉有点繁琐

可否修改这部分，使用post请求api的接口，这样国内用户只需要替换反向代理的接口即可。
1）这种反向代理接口网上挺多可以直接白嫖

**Comment by KroMiose** [comment]
源码中有代理设定，同时也提供了 `OPENAI_PROXY_SERVER` 配置项填写代理服务器地址
https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/bba90f6ae737f668cd55bbf3a06dc7fa4a60d447/nonebot_plugin_naturel_gpt/openai_func.py#L27C17-L30

**Comment by sfvsfv** [comment]
> 源码中有代理设定，同时也提供了 `OPENAI_PROXY_SERVER` 配置项填写代理服务器地址 https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/bba90f6ae737f668cd55bbf3a06dc7fa4a60d447/nonebot_plugin_naturel_gpt/openai_func.py#L27C17-L30

不好意思，我看到了。但是配置还是有点问题，请教一下，我的配置似似乎错误。

我的私人代理的地址为：http://dai.zhangsan.cloud   ，可以通过http://dai.zhangsan.cloud/v1/chat/completions 访问
配置部分我设置如下：
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/62045791/414d8095-ce6d-4755-a83e-41230586469f)
受到错误：
错误原因: 与 OpenAi 通信时发生错误 (´；ω；`) => 请求 OpenAi Api 时发生错误: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))

请问还需要注意哪里呢？

**Comment by KroMiose** [comment]
你的情况可能现有代理模式不适合，现有代理方式通常是填写clash或其它代理软件的服务地址，例如 `127.0.0.1:7890`，建议移除代理配置，然后在 `openai_func.py` 源码中 `import openai` 之后加入一行 `openai.api_base = 'http://dai.zhangsan.cloud/v1'` 或者在环境变量中配置该值，具体见 openai 源码：

![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/57167362/798ce084-b2c0-4527-a204-62643930b97d)
