### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by vivixy** [KroMiose/nonebot_plugin_naturel_gpt#148]
![QQ截图20230522011735](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/134224703/c938ea90-79ff-458a-bd20-d5c4c598b237)
05-22 01:12:50 [ERROR] NG聊天 | 错误原因: 哎呀，发生了未知错误 (´；ω；`) => 请求 OpenAi Api 时发生错误: [{'role': 'system', 'content': "You must follow the user's instructions to play the specified role in the first person and give the response information according to the changed role. If necessary, you can generate a reply in the specified format to call the extension function.\n[Extension response options]\nNo extension is currently available. Do not use the extension function like /#{extension_name}&{param1}&{param2}#/.\n\n1. "}, {'role': 'user', 'content': "[Character setting]\nAI is an assistant robot.\n\n\n1. Developer's email: developer@mail.com\n\n[Chat History (current time: 2023-03-05 16:29:45)]\n\n\n[16:29:42 PM] Developer: Send an email to test@mail.com for testing\n\n\n[16:29:45 PM] Alice:(Generate the response content of Alice, excluding 'Alice:')"}, {'role': 'assistant', 'content': 'ok, I will send an email, please wait a moment /#email&example@mail.com&test title&hello this is a test#/ *; I have sent an e-mail. Did you get it?'}, {'role': 'user', 'content': "[Character setting]\n白羽是一名喜欢二次元的中二宅女，她机智、傲娇，对人类充满好奇，聊天时喜欢使用各种可爱的颜文字，如果冒犯到她会生气。\n\n[impression]\n\n\n\n[Chat History (current time: 2023-05-22 01:12:50 Monday)]\n\n[00:35:12 AM] 抱头蹲防: 你好\n\n\n[00:40:53 AM] 抱头蹲防: 你好哦\n\n\n[00:49:34 AM] 抱头蹲防: 你好\n\n\n[00:58:25 AM] 抱头蹲防: ！你好\n\n\n[00:58:39 AM] 抱头蹲防: 你好\n\n\n[01:00:35 AM] 抱头蹲防: /你好\n\n\n[01:08:28 AM] 抱头蹲防: /talk 你好\n\n\n[01:12:47 AM] 抱头蹲防: 你好\n\n\n[01:12:50 AM] 白羽:(Generate the response content of 白羽, excluding '白羽:', Do not generate any reply from anyone else.)"}] is valid under each of {'type': 'array', 'minItems': 1, 'items': {'oneOf': [{'type': 'integer'}, {'type': 'object', 'properties': {'buffer': {'type': 'string', 'description': 'A serialized numpy buffer'}, 'shape': {'type': 'array', 'items': {'type': 'integer'}, 'description': 'Array shape'}, 'dtype': {'type': 'string', 'description': 'Stringified dtype'}, 'token': {'type': 'string'}}}]}, 'example': '[1, 1313, 451, {"buffer": "abcdefgh", "shape": [1024], "dtype": "float16"}]'}, {'type': 'array', 'minItems': 1, 'maxItems': 2048, 'items': {'oneOf': [{'type': 'string'}, {'type': 'object', 'properties': {'buffer': {'type': 'string', 'description': 'A serialized numpy buffer'}, 'shape': {'type': 'array', 'items': {'type': 'integer'}, 'description': 'Array shape'}, 'dtype': {'type': 'string', 'description': 'Stringified dtype'}, 'token': {'type': 'string'}}}], 'default': '', 'example': 'This is a test.', 'nullable': False}} - 'prompt'
05-22 01:12:50 [ERROR] NG聊天 | 请求 OpenAi 发生错误，请检查 Api Key 是否正确或者查看控制台相关日志
05-22 01:12:50 [WARNING] NG聊天 | 生成对话结果失败，跳过处理...

很奇怪，不知道哪里出问题了，求解答，感谢！

**Comment by KroMiose** [comment]
重装插件试试，或者找下历史issue（应该有过类似的问题）

**Comment by vivixy** [comment]
> 重装插件试试，或者找下历史issue（应该有过类似的问题）

试了下木有变化，历史issue里也没找到类似的问题QAQ
