### ISSUE TITLE
关于最近群聊记忆问题

### ISSUE THREAD

**Issue by Elflare** [KroMiose/nonebot_plugin_naturel_gpt#165]
比如群友A问了个问题Q1，机器人回答了；群友B又问了个问题Q2，因为记忆，机器人回答Q2时又会回答一次Q1，导致常常复读自己的回答。
请问能否在记忆中加个权重（越之前的问题权重越低），或者让机器人自己识别哪些问题已经回答？

**Comment by KroMiose** [comment]
[v2.1.4](https://github.com/KroMiose/nonebot_plugin_naturel_gpt#2023521-v214-%E9%80%BB%E8%BE%91%E4%BC%98%E5%8C%96--%E9%85%8D%E7%BD%AE%E7%83%AD%E9%87%8D%E8%BD%BD) 的更新已优化了该问题，生成响应期间收到新消息会丢弃之前的回答，如果仍然出现该情况，可尝试在人格中加上“不会重复回答已经回答过的问题”

**Comment by Elflare** [comment]
> [v2.1.4](https://github.com/KroMiose/nonebot_plugin_naturel_gpt#2023521-v214-%E9%80%BB%E8%BE%91%E4%BC%98%E5%8C%96--%E9%85%8D%E7%BD%AE%E7%83%AD%E9%87%8D%E8%BD%BD) 的更新已优化了该问题，生成响应期间收到新消息会丢弃之前的回答，如果仍然出现该情况，可尝试在人格中加上“不会重复回答已经回答过的问题”

多谢解答
