### ISSUE TITLE
看不懂的报错

### ISSUE THREAD

**Issue by awkks** [KroMiose/nonebot_plugin_naturel_gpt#166]
看不懂的报错，大佬帮忙看看<img width="867" alt="image" src="https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/110983491/6b22190d-595a-4e39-82da-c34242e878c3">
<img width="867" alt="image" src="https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/110983491/bce88071-33ff-44e6-94ae-68524e2a9acc">第一张是使用对话时出现，第二张是启动时出现

**Comment by KroMiose** [comment]
看起来像是插件文件和记忆文件损坏，尝试重装插件和删除记忆文件试试

**Comment by awkks** [comment]
> 看起来像是插件文件和记忆文件损坏，尝试重装插件和删除记忆文件试试

请问记忆文件是？

**Comment by KroMiose** [comment]
bot目录/data/naturel_gpt/ 下的 .pkl 或 .json 文件

**Comment by awkks** [comment]
> bot目录/data/naturel_gpt/ 下的 .pkl 或 .json 文件

已解决，十分感谢
