### ISSUE TITLE
nonebot消息队列会卡住 

### ISSUE THREAD

**Issue by gunh4mmer** [KroMiose/nonebot_plugin_naturel_gpt#167]
![QQ截图20230602103244](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/73456895/841021dd-630f-436e-ac54-23b5b04def3e)
如上图，go-cqhttp已经收到了31分32分的消息，但是nonebot卡住了，如果按下ctrl+c会批量接受信息如下图
![QQ截图20230602103244](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/73456895/53a156b1-a8fb-45db-9d68-e2b943d87cee)

**Comment by KroMiose** [comment]
偶尔会出现的情况，应该是nb被未知原因阻塞了，具体暂时不明

**Comment by gunh4mmer** [comment]
> 偶尔会出现的情况，应该是nb被未知原因阻塞了，具体暂时不明

另外想问个问题，使用谷歌搜索扩展模块时，会出现如下图的情况
![QQ截图20230602151121](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/73456895/e474d51f-65de-4457-b883-97599961f19d)
![QQ图片20230602151127](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/73456895/33d5ce4a-bbcf-4b65-bd6a-a028d651f57c)

请问这是免费的chatgpt3.5本身的限制回复token数吗，需要升级到4.0？或者说有没有什么办法可以截断（？）bot搜索的内容长度，我在config里面找到了REPLY_MAX_TOKENS（即生成回复的最大 token 数）且已经拉大到了2048仍然提示>1024，但是我记得chatgpt3.5的回复限制是4097，所以很疑惑

**Comment by gunh4mmer** [comment]
> > 偶尔会出现的情况，应该是nb被未知原因阻塞了，具体暂时不明
> 
> 另外想问个问题，使用谷歌搜索扩展模块时，会出现如下图的情况 ![QQ截图20230602151121](https://user-images.githubusercontent.com/73456895/242814312-e474d51f-65de-4457-b883-97599961f19d.png) ![QQ图片20230602151127](https://user-images.githubusercontent.com/73456895/242814334-33d5ce4a-bbcf-4b65-bd6a-a028d651f57c.png)
> 
> 请问这是免费的chatgpt3.5本身的限制回复token数吗，需要升级到4.0？或者说有没有什么办法可以截断（？）bot搜索的内容长度，我在config里面找到了REPLY_MAX_TOKENS（即生成回复的最大 token 数）且已经拉大到了2048仍然提示>1024，但是我记得chatgpt3.5的回复限制是4097，所以很疑惑

或者是否与我选择的是图片输出有关（按理来说应该没关）

**Comment by KroMiose** [comment]
4097的token是请求+回复总量，大部分是预留给行为设定和聊天记录等prompt的，实际回复并没有这么多，并且中文内容消耗的token量巨大(2-3token/字)
