### ISSUE TITLE
求助:基本命令——"rg"(需要加上在NoneBot中设定的指令前缀) 如何添加

### ISSUE THREAD

**Issue by sherlockHlb** [KroMiose/nonebot_plugin_naturel_gpt#17]
基本命令——"rg"(需要加上在NoneBot中设定的指令前缀)
如何添加

**Comment by KroMiose** [comment]
![image](https://user-images.githubusercontent.com/57167362/220592051-4f756a3f-f3ed-4e8f-a88f-aa183270a181.png)
参考图中配置，效果为匹配中文和英文 `!` 开头的指令

**Comment by sherlockHlb** [comment]
了解,还以为要特别配置呢
