### ISSUE TITLE
我想问下，我在使用扩展--发送语音消息 - VOX 版出现后台一直报错

### ISSUE THREAD

**Issue by SuperGuaPi** [KroMiose/nonebot_plugin_naturel_gpt#174]
![LBH83D331OUQGD6M F_33@R](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/90488585/58565b1b-a9b4-4433-a712-1b4fa3ea9243)
这是什么问题，弄了好久都没解决

**Comment by SuperGuaPi** [comment]
![T0 {96(BMI3DSBM8~CX`ABQ](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/90488585/72a4f85f-491c-4d2d-a9e8-56f2848f5e46)
返回是这个值，不懂

**Comment by SuperGuaPi** [comment]
上面两个是开了腾讯翻译出现的问题。

**Comment by KroMiose** [comment]
> 上面两个是开了腾讯翻译出现的问题。 ![image](https://user-images.githubusercontent.com/90488585/255470617-92670d50-1b83-4578-b6ed-d8fef10a0b6d.png) 这个是没开腾讯翻译，返回是一串乱码。

检查下消息中的路径.ogg音频文件是否正常，可能是gocq的超时设定导致直接发送了CQ码

**Comment by SuperGuaPi** [comment]
我看一下

**Comment by KroMiose** [comment]
检查腾讯翻译相关的apikey等参数是否正确填写了（详见yml填写规范），这个问题应该在翻译上

**Comment by SuperGuaPi** [comment]
> > 上面两个是打开腾讯翻译出现的问题。![图像](https://user-images.githubusercontent.com/90488585/255470617-92670d50-1b83-4578-b6ed-d8fef10a0b6d.png)这个是没有打开腾讯翻译，返回是一串乱码。
> 
> 检查下消息中的路径.ogg音频文件是否正常，可能是gocq的超时设置导致直接发送了CQ码

ogg音频文件没有问题，但反馈出的还是源文件地址，这该怎么办

**Comment by SuperGuaPi** [comment]
还有个小问题就是，我在yml文件的扩展配置老是被重置为null是啥情况。
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/90488585/73a1a122-74db-4363-a7b1-b6cdc55d4830)

**Comment by KroMiose** [comment]
详见gocq的 [issue](https://github.com/Mrs4s/go-cqhttp/issues/2010) （可能不是最新方案）

**Comment by SuperGuaPi** [comment]
解决了。🌹
