### ISSUE TITLE
MC是没有服务端了吗

### ISSUE THREAD

**Issue by ayakasuki** [KroMiose/nonebot_plugin_naturel_gpt#175]
好像搜不到nonebot-adapter-spigot这个包了 然后nonebot-adapter-Minecraft没有教程来着

**Comment by KroMiose** [comment]
插件适配的就是 nonebot-adapter-Minecraft 的老版本 (0.0.4) ，建议手动使用pip指令安装

**Comment by ayakasuki** [comment]
好的 我试试



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月01日 11:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [KroMiose/nonebot_plugin_naturel_gpt] MC是没有服务端了吗 (Issue #175) |

插件适配的就是 nonebot-adapter-Minecraft 的老版本 (0.0.4) ，建议手动使用pip指令安装

**Comment by ayakasuki** [comment]
> 插件适配的就是 nonebot-adapter-Minecraft 的老版本 (0.0.4) ，建议手动使用pip指令安装

大大 还有个问题，gpt可以接收到信息，但是回复MC那边收不到，并且回复会适配器短暂not connet
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/20859971/dd8ede23-6c49-448f-a5ff-d9d94e79b2a5)

**Comment by ayakasuki** [comment]
> > 插件适配的就是 nonebot-adapter-Minecraft 的老版本 (0.0.4) ，建议手动使用pip指令安装
> 
> 大大 还有个问题，gpt可以接收到信息，但是回复MC那边收不到，并且回复会适配器短暂not connet ![image](https://user-images.githubusercontent.com/20859971/257989682-dd8ede23-6c49-448f-a5ff-d9d94e79b2a5.png)

这个应该是rcon直接发送到mc才对 但是mc确实没收到来着——，是对jar有什么版本要求嘛

**Comment by KroMiose** [comment]
普通消息走的不是RCON，只有指令才是，如果不需要执行指令的话可以不开RCON的；发送过去的消息能否发送到聊天和MC服务端的spigot适配有关，确认下MC那边的适配插件是否正常加载了，与nb的连接是否稳定，还有就是和服务端的类型和版本也有关系，我只在spigot端上测试成功了，其他端没有具体测试

**Comment by ayakasuki** [comment]
原来如此 目前是必须水龙头端对吧

> 普通消息走的不是RCON，只有指令才是，如果不需要执行指令的话可以不开RCON的；发送过去的消息能否发送到聊天和MC服务端的spigot适配有关，确认下MC那边的适配插件是否正常加载了，与nb的连接是否稳定，还有就是和服务端的类型和版本也有关系，我只在spigot端上测试成功了，其他端没有具体测试

**Comment by ayakasuki** [comment]
> 原来如此 目前是必须水龙头端对吧
> 
> > 普通消息走的不是RCON，只有指令才是，如果不需要执行指令的话可以不开RCON的；发送过去的消息能否发送到聊天和MC服务端的spigot适配有关，确认下MC那边的适配插件是否正常加载了，与nb的连接是否稳定，还有就是和服务端的类型和版本也有关系，我只在spigot端上测试成功了，其他端没有具体测试

目前试过fabric，好像不行—— 那就只能先不接入mc了

**Comment by KroMiose** [comment]
具体能否适配取决于适配端的实现，mcqq那边有日志监听的方案等，理论上应该能适配所有端

**Comment by ayakasuki** [comment]
> 具体能否适配取决于适配端的实现，mcqq那边有日志监听的方案等，理论上应该能适配所有端

我是用他那个[Minecraft_Server.jar](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/download/v1.2.6-post1/Minecraft_Server.jar)来着

**Comment by KroMiose** [comment]
那个是插件，fabric端只能加载mod
