### ISSUE TITLE
[BUG?] 触发逻辑问题

### ISSUE THREAD

**Issue by HuYo-OS** [KroMiose/nonebot_plugin_naturel_gpt#176]
生成的内容由bot发送后，如果内容带有自己的人格名会误触发，会再发送一次之前生成的内容，然后又触发，从而陷入死循环

**Comment by KroMiose** [comment]
正常回复是不会触发自己的，但是扩展的返回内容有可能触发，是否有复现的情况截图？

**Comment by HuYo-OS** [comment]
很遗憾，暂时复现不了，貌似这种情况，似乎是偶发性的，也有可能是群友的自定义人格的问题

通过翻看DEBUG日志，我发现这种情况发生时 bot 的 self_id 和 用户的 user_id 是一致的
然后我通过更改**do_msg_response**函数下的 `判断是否需要回复` 的判断条件
把
```python
(config.REPLY_ON_NAME_MENTION and (chat.preset_key.lower() in trigger_text.lower())) or \
```
更改为
```python
(config.REPLY_ON_NAME_MENTION and (chat.preset_key.lower() in trigger_text.lower()) and trigger_userid != bot.self_id) or \
```
临时解决了该问题

感谢作者的回复
