### ISSUE TITLE
增加个bing吧，球球了，gpt的access_token也行，api key太难搞了。还有就是运行时提示需要装htmlrender才能文字转图，但我装了后两个插件都出BUG无法运行，是有什么冲突吗？

### ISSUE THREAD

**Issue by EiyoV** [KroMiose/nonebot_plugin_naturel_gpt#177]
安装nonebot-plugin-htmlrender前![1](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/137661049/5658bb16-721e-4069-bcf0-16406deae6f4)
安装后![2](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/137661049/1096ba7e-13ff-447b-8c7d-b91329a6edb1)
![3](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/137661049/2cb08979-8eaf-4bc6-9e0d-7370cff399f8)
![4](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/137661049/50358c76-5be5-49d2-aba0-de5826eed28e)

**Comment by KroMiose** [comment]
bing的prompt没法完全定制，加上ng的prompt为了尽可能降低成本实现各种复杂功能调用，预计支持了效果也不会太好；另外你的报错信息没有截完整，无法定位问题，一般最关键的错误信息在报错内容的末尾
