### ISSUE TITLE
使用rg del删除人格显示错误

### ISSUE THREAD

**Issue by LycanW** [KroMiose/nonebot_plugin_naturel_gpt#178]
对于使用rg new创建的人格，使用rg del删除的时候提示：执行命令时出现错误: list index out of range
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/87530173/b124065f-b512-4382-996c-1eda79ce3157)

**Comment by KroMiose** [comment]
建议尝试使用rg del -global全局删除
