### ISSUE TITLE
Bot回复乱码

### ISSUE THREAD

**Issue by radicalyyyahaha** [KroMiose/nonebot_plugin_naturel_gpt#179]
<img width="347" alt="屏幕截图 2023-09-26 115425" src="https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/124671808/d0fb9644-eae4-4df3-b8de-8bd86d907109">
<img width="692" alt="image" src="https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/124671808/050f7db0-0eda-478a-bc9f-fb0a74a11021">

昨天还好好的，今天突然开始乱码了。。。其他插件回复文字都是正常的

**Comment by KroMiose** [comment]
没见过的问题。。可能与人设有关，这个应该就是接口返回的原文本

**Comment by radicalyyyahaha** [comment]
> 没见过的问题。。可能与人设有关，这个应该就是接口返回的原文本

可能是bot长大了有自己的人格了（悲
