### ISSUE TITLE
readme说的 poetry，poetry没有--dev 选项

### ISSUE THREAD

**Issue by 2catycm** [KroMiose/nonebot_plugin_naturel_gpt#184]
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/41530341/d3d845d8-ec32-4dd4-90e9-b7cd9a8a073c)
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/41530341/c8f2cb82-7e72-474f-aea4-ba063a7d5694)

我搜索了很久，没看懂poetry的文档，文档中显示确实没有这个命令https://python-poetry.org/docs/cli/
那么readme这里想要加上dev的目的是什么呢？有没有相似的命令可以取代它的功能

**Comment by KroMiose** [comment]
感谢反馈！这里的命令有误，改为 `poetry install` 即可

经过测试，`--dev` 只有 poetry add 开发环境安装开发依赖包时可用，poetry的包管理策略是执行 `poetry install` 的时候即自动安装所有包，包括开发环境和非开发环境包，此处的 `--dev` 原意是为了指定需要同时安装开发环境包，但是 `poetry install` 时已经默认包含上了开发依赖，如果不安装开发依赖则需要添加上 `--no-dev` 参数
