### ISSUE TITLE
拓展如何使用？

### ISSUE THREAD

**Issue by Esmge** [KroMiose/nonebot_plugin_naturel_gpt#186]
能不能在文档中给出触发拓展使用的指令参考？比如生成图片的？

**Comment by KroMiose** [comment]
查看控制台日志输出是否显示扩展被成功加载，如果成功加载了直接叫ai发送图片；你的需求下直接发“发送一张萝莉图”即可，如果出现"cant't assist with that request"是因为请求被openai风控拦截，原因是包含敏感内容等，建议更换模型或者尝试其他问题
