### ISSUE TITLE
胡言乱语

### ISSUE THREAD

**Issue by yamadafz** [KroMiose/nonebot_plugin_naturel_gpt#187]
请问这种情况怎么解决
![image](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/assets/98805571/883b6bab-60fd-4e06-a8d4-fed6a71f6aa8)

**Comment by KroMiose** [comment]
可能是提示词中含有openai禁止内容，请尝试 换模型/修改人设/关闭限制模式

**Comment by yamadafz** [comment]
> 可能是提示词中含有openai禁止内容，请尝试 换模型/修改人设/关闭限制模式

但我这是默认人设，切换人设也是这样，有时候能输出正常的内容，我觉得是哪里缓存有问题

**Comment by KroMiose** [comment]
使用的是官方api吗？

**Comment by yamadafz** [comment]
> 使用的是官方api吗？

是的

**Comment by KroMiose** [comment]
尝试其他模型试试，切换后需要 rg reset 清除记录避免ai从上文再学到一样的内容回复，如果使用了第三方的逆向api等也可能出现这个问题，另外普通版本的3.5优于16k版本的表现
