### ISSUE TITLE
配置文件中添加代理选项

### ISSUE THREAD

**Issue by HMScygnet** [KroMiose/nonebot_plugin_naturel_gpt#19]
服务器上不是很方便使用全局代理，直连又经常出现对话卡死现象，希望能在配置文件中自行填写代理地址

**Comment by KroMiose** [comment]
感谢建议，当前使用的是openai官方的sdk，并不支持直接设置代理，未来会考虑改用原生requests请求

**Comment by HMScygnet** [comment]
> 感谢建议，当前使用的是openai官方的sdk，并不支持直接设置代理，未来会考虑改用原生requests请求

openai sdk是可以设置代理的
`openai.proxy='代理地址'`即可设置，已经实验过了是可行的

**Comment by KroMiose** [comment]
好的！下个版本加入 ( •̀ ω •́ )✧

**Comment by KroMiose** [comment]
感谢！下个版本跟随chatgpt模型接入一同更新
