### ISSUE TITLE
关于白名单的问题

### ISSUE THREAD

**Issue by F1Justin** [KroMiose/nonebot_plugin_naturel_gpt#193]
是否可以设置群组和个人的白名单？（黑名单在不希望让很多群与个人都能聊天的情况下有些麻烦

**Comment by KroMiose** [comment]
可以使用批量 off 命令关闭掉所有会话，然后针对特定群组和个人单独开启（具体命令请参考文档站）

**Comment by F1Justin** [comment]
但是似乎bot被拉进新群之后，还是默认开启的，所以还是不能起到白名单的效果

**Comment by KroMiose** [comment]
新会话默认是不生效的，这个需求只能通过修改源码处理，或者直接禁止bot被随意拉群
