### ISSUE TITLE
第三方OPENAI SDK支持问题

### ISSUE THREAD

**Issue by lixz123007** [KroMiose/nonebot_plugin_naturel_gpt#200]
大佬你好。
官方的API真的太难搞了。现在注册页不送，还需要信用卡。但是第三方的key，价格还是可以接受的。
能否支持一下第三方api。
加个API server设置。
或者大佬告诉一下源码哪里可以改？

**Comment by KroMiose** [comment]
配置文件里面可以改，有个base url字样的字段
