### ISSUE TITLE
能否升级openai库至1.45.1版本

### ISSUE THREAD

**Issue by Momo-Tori** [KroMiose/nonebot_plugin_naturel_gpt#202]
最近使用该库调用deepseek的api端口，但deepseek方面会返回报错json序列化失败的bug

将openai库升级至最新版本后并将openai_func.py中的openai调用修改为正确的调用形式后可以正确运行

想咨询一下是否有计划将openai依赖升级到最新的版本？

**Comment by KroMiose** [comment]
目前没有相关计划哦，现在主要精力在新项目 nekro-agent  上
