### ISSUE TITLE
佬。关于本地有ai语音合成文件能不能将其导入进去，而不是使用网页api的那种

### ISSUE THREAD

**Issue by TTnpow** [KroMiose/nonebot_plugin_naturel_gpt#23]
像nonebot-plugin-tts-gal的发送语音方式

**Comment by KroMiose** [comment]
可以直接使用本地文件，实际上当前的语音拓展模块也是先把网页api调用的合成语言缓存到本地再发送的，否则容易失败

**Comment by TTnpow** [comment]
# todo: 如果需要使用本地的语音合成api，请取消注释下面的代码，并自行改为您的api地址
        #url = f"https://huggingface.co/spaces/sayashi/vits-models>; rel="canonical"
是只要将这行注释取消掉然后把模型的pth文件或者json文件地址放进去就行了对吧

**Comment by KroMiose** [comment]
并不是，语音合成的vits没有集成在本插件中，你需要另外自行搭建vits服务器（可以是远程也可以是本地），然后把调用api填写到这里的url，拓展会请求这个url然后把生成的语音文件缓存到本地再转交给gocq发送

**Comment by TTnpow** [comment]
哦哦，学会了，谢谢佬
