### ISSUE TITLE
开启后导致别的插件无法响应消息

### ISSUE THREAD

**Issue by Fsyxr** [KroMiose/nonebot_plugin_naturel_gpt#3]
比如nonebot_plugin_word_bank2,nonebot_plugin_osubot,我在启用本插件后,使用之前的命令就无法触发响应,但是nonebot_plugin_aecaeabot这个插件还是可以响应
![123](https://user-images.githubusercontent.com/85301551/216243004-ad2d18cc-a23f-4af4-b05c-44a1f880f6cf.png)

**Comment by KroMiose** [comment]
该问题是插件拦截了消息向低优先级插件传递引起的，可参考临时解决方案：修改本插件__init__,py第177行，提高priority或者设置block为False，下个版本将针对此问题进行修复
