### ISSUE TITLE
启动时出现报错

### ISSUE THREAD

**Issue by pshta0** [KroMiose/nonebot_plugin_naturel_gpt#30]
我第一次尝试使用Nonebot ! 装后尝试启动时出现该报错
![QQ图片20230305234208](https://user-images.githubusercontent.com/122964169/222970553-6e4f9d5f-841b-417b-b644-10758f35a4c8.png)

**Comment by KroMiose** [comment]
从你提供的信息种无法看出问题，请补充更详细的错误信息
