### ISSUE TITLE
[建议] 希望能够重构 __init__ 内的各个函数

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [KroMiose/nonebot_plugin_naturel_gpt#31]
nonebot_plugin_naturel_gpt/__init__.py 里的各个函数，比如 identity:Matcher 大量重复代码，建议重构，把重复代码抽取为函数，并且将权限验证逻辑独立为函数，且在调用时通过变量调用，以方便使用外部第三方的验证函数

**Comment by KroMiose** [comment]
重构有在计划中，主要难点是init中使用的公共变量较多，关系比较复杂，指令和权限管理部分打算重写，随着迭代进行导致指令集越来越多，原本的结构确实不能满足了

**Comment by Misaka-Mikoto-Tech** [comment]
另外建议每个 chat_key(群/私聊）的预设人格都独立设定

**Comment by KroMiose** [comment]
这个就比较难以实现了...人格预设的整体架构冲突比较大，改起来难度可能不亚于重写 /_ \

**Comment by Misaka-Mikoto-Tech** [comment]
> 这个就比较难以实现了...人格预设的整体架构冲突比较大，改起来难度可能不亚于重写 /_ \

我觉得可以没有修改时使用全局预设，用户修改以后使用用户自定义的预设条目覆盖默认预设相应条目

**Comment by KroMiose** [comment]
感谢建议，有时间重构的话再参考下哈 (ง •_•)ง

**Comment by Misaka-Mikoto-Tech** [comment]
好的，另外demo里的请求是 `openai.Completion.create`, 其实还有个 `openai.Completion.acreate` 是异步的，我看你代码是用 @run_sync 创建的异步，其实是可以直接定义 async def get_response()  函数的

**Comment by KroMiose** [comment]
其实协程和异步这一块的内容我也是萌新哈， `@run_sync` 的部分其实是另一位大佬给的 pr，当时解决了给openai设置了规定时间timeout但无效仍会导致整个程序卡住六分钟左右才抛出错误的问题（v1.4.4的更新），目前看来这部分工作情况还算正常，我会再仔细学习的，感谢大佬指点！

**Comment by Misaka-Mikoto-Tech** [comment]
今天发现两个问题
一个是让bot写代码，chatgpt发送的代码被包裹在 markdown 的 ``` 里，然后代码就被过滤掉了。
第二个问题是openai 的服务器不稳定，经常出 500 Internal Error 和 未知错误让你给它发邮件报告，因此我建议 get_response 对包含 `500` 和 `help.openai.com` 文本的错误再尝试请求一次（获取可以先 sleep 一小段时间）

**Comment by KroMiose** [comment]
代码包含在markdown的```中其实是[prompt](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/aaa095e036ccde76dce9dab359f91546e0332fbd/nonebot_plugin_naturel_gpt/__init__.py#L255-L258)中刻意要求的，主要是为了便于提取代码，考虑为以后做图片渲染预留（如果有的话），但是代码被过滤掉的情况倒比较少见，今天使用的适合还是正常的
![image](https://user-images.githubusercontent.com/57167362/223426373-2fd3f2f7-a2bc-479a-953b-c64d446e9e2c.png)
但是我刚才去看了下[源码](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/aaa095e036ccde76dce9dab359f91546e0332fbd/nonebot_plugin_naturel_gpt/__init__.py#L941)
现在倒有些疑惑为什么不会把代码过滤掉了 （⊙ｏ⊙）

500error这个问题倒是今天才出现，我在两台服务器部署的bot有一台（在香港）今天一直不太稳定，可以加入请求重试，另外错误处理这块目前只做了[一小部分](https://github.com/KroMiose/nonebot_plugin_naturel_gpt/blob/aaa095e036ccde76dce9dab359f91546e0332fbd/nonebot_plugin_naturel_gpt/openai_func.py#L45-L58)，我偶尔有收集群里的各种报错情况，尝试把容易解决的错误都做下日志提示，方便用户使用时自主排查
