### ISSUE TITLE
[建议]增加原生ChatGpt聊天功能，私聊会话增加记忆清除功能，增加可设定用户自定义私有人格功能


### ISSUE THREAD

**Issue by itsevin** [KroMiose/nonebot_plugin_naturel_gpt#32]
＃＃ 增加原生ChatGpt聊天功能

有些用户只是单纯想使用ChatGpt，而不想要多余设定

＃＃ 私聊会话增加记忆清除功能

有的时候需要训练ChatGpt，训练失败时需要重置记忆（重置会话）

＃＃ 增加可设定用户自定义私有人格功能

有些用户想要设定私有人格，不想让他人看见

**Comment by KroMiose** [comment]
单纯chatgpt目前通过修改人设可以比较接近原生效果，但由于本插件主要对群聊的场景做了优化和为了支持拓展使用，很难达到原生效果

会话清除方面目前有rg reset可以清除上下文记忆，但是尚不能清除用户印象

私有人格这个需要考虑下，可能有其他方式可以实现类似的效果

**Comment by eigeen** [comment]
接近原生ChatGPT的效果，推荐使用rg new ChatGPT You are a helpful assistant. Use Chinese only. 等类似方法实现。

因为插件的人格设定实际上是通过更改api的system字段实现的，=具体内容可以查看openai的文档里的样例

**Comment by itsevin** [comment]
前两点没问题，作者对私有人格有什么看法？有什么办法实现类似效果吗？

**Comment by KroMiose** [comment]
目前版本已经是每个会话独立人格了，用户直接添加bot好友即可完全控制自定义人格，并且不会全局共享
