### ISSUE TITLE
插件运行问题

### ISSUE THREAD

**Issue by ability66** [KroMiose/nonebot_plugin_naturel_gpt#34]
貌似每次启动如果想得到回应需要挂梯子，请问有办法不挂梯子就能得到回复吗
不挂梯子就是这样
![image](https://user-images.githubusercontent.com/106503132/223618910-d4e4b6d7-a6c6-44a6-843b-cd94b2b684a0.png)
感谢大佬

**Comment by KroMiose** [comment]
暂时没有办法呢，以前是可以直连的，最近墙变高了，如果有条件可以使用香港或者境外的云服务器
