### ISSUE TITLE
百度扩展让他搜什么都是搜索失败

### ISSUE THREAD

**Issue by CCYellowStar** [KroMiose/nonebot_plugin_naturel_gpt#39]
[ext_baidu] 未找到关于＊＊＊的百科信息

**Comment by KroMiose** [comment]
搜索拓展暂时没法用，百度那边不吐信息，建议先禁用此拓展

**Comment by CCYellowStar** [comment]
> 搜索拓展暂时没法用，百度那边不吐信息，建议先禁用此拓展

我禁用之后ai会不会还记得这个拓展然后继续尝试使用（）

**Comment by KroMiose** [comment]
禁用后指令表中就不会出现该指令了，另外可以再reset一下清除上下文记忆，避免bot从上下文中学到错误的指令使用

**Comment by CCYellowStar** [comment]
https://ddg-webapp-aagd.vercel.app/search?q={content}?&max_results={result_nums}&region=cn-zh

找到个不知道怎么用的api

**Comment by KroMiose** [comment]
感谢，这个api有一定参考价值，我找到了一个可以读取网站内容的接口 https://ddg-webapp-aagd.vercel.app/url_to_text?url=https://blog.csdn.net/hff945/article/details/113664544 ，还找到了原github仓库：https://github.com/qunash/ddg-webapp，我会再尝试发掘一些看如何应用，有望实现接近newbing的效果（虽然可能会比较费token）
