### ISSUE TITLE
需要翻墙才能使用吗？使用命令没反应，但是对话会提示失败

### ISSUE THREAD

**Issue by saferabbit** [KroMiose/nonebot_plugin_naturel_gpt#4]
bot：zhenxunbot
系统：Ubuntu 20.04
问题描述：
使用命令没反应，对话会显示连接openai失败或者API失败。有时又正常
日志报错：
```
02-09 18:30:16 [WARNING] extensive_plugin | 当前 Api Key 失效，正在尝试使用下一个 Api Key
02-09 18:30:16 [ERROR] extensive_plugin | 无法连接到 OpenAi 或者当前所有 Api Key 失效
02-09 18:30:16 [WARNING] apscheduler | Run time of job "_ (trigger: interval[0:05:00], next run at: 2023-02-09 18:35:13 CST)" was missed by 0:00:02.502746
```
我配置文件有错吗？
![image](https://user-images.githubusercontent.com/44218328/217787005-08360fe1-288e-4c9c-a92b-f8dca5b3df05.png)

**Comment by saferabbit** [comment]
> 正常来说国内大部分地区可以直接访问openai的api，如果有时可以正常有时失败说明配置文件是正确的，大概率是对openai的api访问不稳定，可以尝试挂梯子看能否改善

今天都正常，可能昨天网络有问题。想问下相关指令怎么触发呢？没触发到菜单之类的指令

**Comment by saferabbit** [comment]
还有，这人格设置，感觉不会回答你的很多实际问题？要怎么切换？

**Comment by KroMiose** [comment]
基本命令是 `rg` ，如果您有在nb中设置指令前缀的话要加上前缀才会被匹配，例如设置指令前缀为 `!` ，触发命令帮助的指令就是 `!rg`，其他指令（包括切换人格和设置等）同理，基本上都是 `!rg xxx` 的形式

**Comment by saferabbit** [comment]
> 基本命令是 `rg` ，如果您有在nb中设置指令前缀的话要加上前缀才会被匹配，例如设置指令前缀为 `!` ，触发命令帮助的指令就是 `!rg`，其他指令（包括切换人格和设置等）同理，基本上都是 `!rg xxx` 的形式

尝试过了，没反应也没报错，是我的bot自身冲突了？没有前缀，无论是rg XXX，人格 XXX和人格设定 XXX都没反应

**Comment by KroMiose** [comment]
尝试在 .env 中的 `COMMAND_START=["!", "！"]` 配置一下指令前缀试试？我在开发时确实没有测试过无前缀的指令情况，因为对nb框架的开发还不是很熟悉，如果确认是无前缀引起的异常我会在下个版本中处理一下。
另外无前缀（ `COMMAND_START=[]` ）和空前缀（ `COMMAND_START=[""]` ）是两种不同的状态，按我的理解，无前缀应该是不会匹配任何命令，空前缀则是匹配所有内容都当作命令处理

**Comment by saferabbit** [comment]
> 尝试在 .env 中的 `COMMAND_START=["!", "！"]` 配置一下指令前缀试试？我在开发时确实没有测试过无前缀的指令情况，因为对nb框架的开发还不是很熟悉，如果确认是无前缀引起的异常我会在下个版本中处理一下。 另外无前缀（ `COMMAND_START=[]` ）和空前缀（ `COMMAND_START=[""]` ）是两种不同的状态，按我的理解，无前缀应该是不会匹配任何命令，空前缀则是匹配所有内容都当作命令处理

添加前缀后可以查看菜单了，也正常了。感觉大佬回答

**Comment by KroMiose** [comment]
不客气！欢迎持续关注更新ヾ(≧▽≦*)o
