### ISSUE TITLE
我想问下发送邮件的插件该怎么设置

### ISSUE THREAD

**Issue by PROBEFISH** [KroMiose/nonebot_plugin_naturel_gpt#43]
我已经按说明配置填好了授权码和邮箱地址，可还是没办法向指定的邮箱发送邮件，后台的提示也是调用拓展email时发生错误:(535,b'Error:authentication failed')
我需要改哪里吗，还是说有哪部做错了

**Comment by KroMiose** [comment]
![image](https://user-images.githubusercontent.com/57167362/224248985-3d511e8a-5857-4bf0-ba5b-fbf55fcbbf86.png)
参考这个填写方式，目前只支持网易邮箱，其他邮箱需要修改smtp服务器地址

**Comment by PROBEFISH** [comment]
我改成163的邮箱就可以了
