### ISSUE TITLE
聊天记录会串线,以及无法清空记录

### ISSUE THREAD

**Issue by gitxxp** [KroMiose/nonebot_plugin_naturel_gpt#44]
![image](https://user-images.githubusercontent.com/33143774/224314315-82b598dc-68a4-467e-8308-78bf7293c972.png)
无法清空记录,想开新话题都会和前文混淆,而且群聊的内容任然会串线到私聊里,希望私聊内容不会窜到群里.
另外,在群聊中的回复能否在消息前艾特那个回复对象或者引用那个提问

**Comment by KroMiose** [comment]
因为reset只清除掉了上下文，并没有清除掉用户印象，另外目前版本是多个会话公用一套用户印象，下一个版本重构后会改为每个会话独立

**Comment by gitxxp** [comment]
> 因为reset只清除掉了上下文，并没有清除掉用户印象，另外目前版本是多个会话公用一套用户印象，下一个版本重构后会改为每个会话独立; bot回复行为具体控制可以通过编辑人设来实现

有清除用户印象的方法吗，目前很容易乱套了，或者下个版本可以增加取消记录印象的指令吗，因为有时候只是想单纯使用原生ChatGpt，而不想要多余设定

**Comment by KroMiose** [comment]
目前开发重心主要在重构后的调试和优化，用户印象功能后续还会有调整，会考虑加入相关功能哈
