### ISSUE TITLE
机器人对于任何命令都没有任何反应是什么原因？

### ISSUE THREAD

**Issue by 0ceanCat** [KroMiose/nonebot_plugin_naturel_gpt#50]
可以运行，但是哪怕我发送rg等关键词他也没有任何反应。断点打的满代码都是，不论我发送什么文本唯一执行的函数就是：
![image](https://user-images.githubusercontent.com/58326657/224504074-9f0e53db-b163-4121-b56f-3b24758a750f.png)

无法指定人格，无法切换人格，总之就是没有反应233
help

**Comment by KroMiose** [comment]
检查是否正确配置了nonebot的指令前缀，发送指令时会先根据nonebot的匹配规则走指令响应器（即要带上在nonebot的env中配置的指令前缀，或者可配置为无前缀）

**Comment by jisadamio** [comment]
能接收到指令但不能记忆 记忆模块那
![30 7_1`LL3@Z W`Y`)IU(M9](https://user-images.githubusercontent.com/127448275/225259030-6327785d-e79c-4f6e-88db-7daf7e9cf164.png)
![0}3I0L)AMWG6G2}7QXJ{H0U](https://user-images.githubusercontent.com/127448275/225259069-df42154b-f9f6-48f6-98e9-1026eaf6ee23.png)

**Comment by KroMiose** [comment]
@jisadamio 记忆模块由于bot使用调教效果不佳，暂时不推荐启用，目前开发重心主要在重构，后续会有新的记忆方案
