### ISSUE TITLE
是默认不走代理吗，挂了梯子也提示‘无法连接到 OpenAi 或者当前所有 Api Key 失效’

### ISSUE THREAD

**Issue by nnnn0088** [KroMiose/nonebot_plugin_naturel_gpt#6]
是默认不代理吗，挂了梯子也提示‘无法连接到 OpenAi 或者当前所有 Api Key 失效’

02-10 15:21:40 [WARNING] nonebot_plugin_naturel_gpt | 当前 Api Key 失效，正在尝试使用下一个 Api Key

02-10 15:21:40 [ERROR] nonebot_plugin_naturel_gpt | 无法连接到 OpenAi 或者当前所有 Api Key 失效

02-10 15:21:42 [INFO] nonebot_plugin_naturel_gpt | token消耗: 579 | 对话响应: "哎呀，OpenAi Api 好像挂了呢 (´；ω；`)"

02-10 15:21:42 [INFO] nonebot_plugin_naturel_gpt | [会话: private_379045610]添加对话历史行: 白: 哎呀，OpenAi Api 好像挂了呢 (´；ω；`)

  |  当前对话历史行数: 10

02-10 15:21:42 [INFO] nonebot_plugin_naturel_gpt | 添加对话历史行: 白: 哎呀，OpenAi Api 好像挂了呢 (´；ω；`)

  |  当前对话历史行数: 14

![截图20230210152546](https://user-images.githubusercontent.com/124555182/218028770-940408db-6445-4ca8-a2d1-0da85823a668.png)

**Comment by KroMiose** [comment]
插件没有对代理等网络配置做指定，应该是跟着系统的，尝试挂全局代理，或者在规则代理中手动添加openai.com的域名？
