### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by Nenot233** [KroMiose/nonebot_plugin_naturel_gpt#7]
1.是否可以重置聊天，群友教的东西太杂了，有没有办法指令重置
2.回答聊天会行等待，导致其他指令延时触发，是否能同时就行（表现为卡顿，主要解决卡顿）

**Comment by KroMiose** [comment]
感谢反馈！
1. 重置功能是可以加的，但具体重置哪些信息尚需研究一下，下个版本可能会加入
2. 卡顿问题是因为消息不是异步处理的，主要是因为对nb的使用理解不够深入，会继续尝试解决看能不能做成异步处理，其实目前主要的处理时间是消耗在token数计算上，而不是回复生成，具体原因暂时不明，敬请期待后续版本更新

**Comment by KroMiose** [comment]
@Nenot233 最新版已更新了异步处理，消息处理速度得到了一定提升；重置功能已在上一个版本加入
