### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by chenwei1999** [KroMiose/nonebot_plugin_naturel_gpt#71]
大佬您好，测试发现这种 proxy 的方式不支持 socks 代理

**Comment by KroMiose** [comment]
@Misaka-Mikoto-Tech 大佬测试了，行不通
![DSYPA1@~M~O3D4)3_U@AW`T](https://user-images.githubusercontent.com/57167362/225513391-ac30c614-51af-442c-8455-3279ba51b5f2.png)
另外即使可行，会导致全局所有使用requests的请求均走了代理，可能导致其它插件异常或者一些难以预计的错误
