### ISSUE TITLE
能不能通过聊天指令来控制ai的触发命令

### ISSUE THREAD

**Issue by lintonxue00** [KroMiose/nonebot_plugin_naturel_gpt#72]
可以在聊天群里通过输入#rg 触发 方式，方式可以是@或者触发概率，来修改触发的方式，也可以考虑通过指令让每个群的触发概率都不一样。我发现修改配置文件好像不能生效，还是保持原有的方式。

**Comment by KroMiose** [comment]
通过指令控制修改配置文件部分设定的方案有在考虑，预计会在重构版合并后的后续版本再进行
