### ISSUE TITLE
关于回复的问题

### ISSUE THREAD

**Issue by Yunmo-1** [KroMiose/nonebot_plugin_naturel_gpt#73]
![image](https://user-images.githubusercontent.com/79674967/225580122-ec893b6c-7144-485a-a9b4-b935fc6fbc9c.png)
![image](https://user-images.githubusercontent.com/79674967/225580177-f5865c3f-d1fa-4898-8191-a8e39bf4ae31.png)
在有些群回复带名字前缀，这个怎么去掉啊

**Comment by ILYSHL** [comment]
用的插件版本是main的最新版本吗

**Comment by KroMiose** [comment]
编辑人设并把人设中的“习惯自称：xxx”去掉即可
