### ISSUE TITLE
能否对接openAI的ChatGPT

### ISSUE THREAD

**Issue by YouYouLip** [KroMiose/nonebot_plugin_naturel_gpt#8]
因为GPT的模型都是来源于playground 是有额度的，但是chatGPT可以免费用 不知道以后能不能对接ChatGPT的token

**Comment by YouYouLip** [comment]
而且sms现在坐地起价 把关于openAI的虚拟手机号价格全部提高 我记得平均都是10卢布左右 现在平均被提到了50卢布

**Comment by KroMiose** [comment]
有其他大佬做了对接chatgpt尝试，但是因为现在chatgpt现在热度太高，即使是直接使用官方的网页访问也很不稳定，效果体验不会太好；另外chatgpt虽然目前是免费的，但是我个人预估不久就会转为收费使用了，或许以后研究如何对接新bing更合适（？
账号价格方面确实没什么办法，我自己也没渠道搞新的key了，仅剩不多的以前屯的key了（悲
