### ISSUE TITLE
运行重构后的项目不能用关键词切换人格

### ISSUE THREAD

**Issue by linngdu664** [KroMiose/nonebot_plugin_naturel_gpt#86]
运行项目重构前的版本可以通过关键词直接切换人格，更新重构后的版本后发现喊当前人格的名字能直接召唤，但喊不是当前人格的名字则不会召唤，控制台会说不是bot相关信息。
配置文件：
NG_ENABLE_AWAKE_IDENTITIES: true
REPLY_ON_NAME_MENTION: true

**Comment by KroMiose** [comment]
在需要启用切换的会话中使用rg unlock解锁人格切换
