### ISSUE TITLE
设置代理后出现了SSLError错误

### ISSUE THREAD

**Issue by youmingsama** [KroMiose/nonebot_plugin_naturel_gpt#87]
多次更改节点后仍然报错
![A6D`@RN F% QZC(`8GQ7L 1](https://user-images.githubusercontent.com/48556744/226187801-60cef7da-ff87-4ff0-95ce-54b6a4ef02e1.png)

**Comment by ILYSHL** [comment]
不要开系统代理，确认下代理端口和配置文件OPENAI_PROXY字段填写正确。一定要用系统代理的话命令行得代理。

**Comment by youmingsama** [comment]
> 不要开系统代理，确认下代理端口和配置文件OPENAI_PROXY字段填写正确。一定要用系统代理的话命令行得代理。

好捏，不过已经结局了，换了一些节点就没问题了
