### ISSUE TITLE
多个api读取失败

### ISSUE THREAD

**Issue by YouYouLip** [KroMiose/nonebot_plugin_naturel_gpt#9]
raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config/naturel_gpt_config.yml", line 1, column 1
expected <block end>, but found '['
  in "config/naturel_gpt_config.yml", line 14, column 73
错误代码
![image](https://user-images.githubusercontent.com/119958263/218247554-1c7f40db-246f-4f66-89b2-32b434303839.png)
是我配置写错了吗 应该怎么分列呢

**Comment by KroMiose** [comment]
![image](https://user-images.githubusercontent.com/57167362/218248359-ba373f8d-8efe-470b-966d-623f60f04d3c.png)
按照yaml方式编写即可，参考图中方式配置

**Comment by YouYouLip** [comment]
> 

感谢 已解决问题
