### ISSUE TITLE
[建议] 希望降低 `未找到拓展 null，跳过调用` 这个日志的等级

### ISSUE THREAD

**Issue by he0119** [KroMiose/nonebot_plugin_naturel_gpt#91]
因为时不时会出现， 但其实已经被跳过，也没有什么影响。降低等级之后，sentry 就不会捕获这条日志。

**Comment by KroMiose** [comment]
hmm这个情况其实还蛮少见的，调教正常的话bot很少会去调用不存在的拓展，显示这个提示也是为了帮助用户检查安装的拓展是否正常工作，日志方面目前来看确实有些冗长，会再进行调整
