### ISSUE TITLE
[bug]绘画拓展bug

### ISSUE THREAD

**Issue by Elijah-0616** [KroMiose/nonebot_plugin_naturel_gpt#93]
我目前使用的插件版本为2.0.1，绘画拓展可以使用，但返回的图片有问题，貌似是图片的编码？点击控制台的链接可以在浏览器查看图片。
对话和控制台日志如下：
**我注意到有一行说到转换消息到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).** 不知道问题是不是在这里
<img width="329" alt="image" src="https://user-images.githubusercontent.com/60286615/226633352-df07a8d6-d821-4395-a5d6-930e18c86f57.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/60286615/226633621-23ad426a-a2f1-4e6d-9afe-50754ad47324.png">

**Comment by ILYSHL** [comment]
先问一下其他图片也是编码还是只有调用paint发送的图片有问题呢

**Comment by Elijah-0616** [comment]
> 先问一下其他图片也是编码还是只有调用paint发送的图片有问题呢

刚刚试了其他发图的插件，能正常返图，但那个插件是用的转发消息的方式，不知道直接发图会不会有问题
https://github.com/ayanamiblhx/nonebot_plugin_setu
这个插件可以正常发图

**Comment by KroMiose** [comment]
@Elijah-0616 hmm不是其它插件，而是其它的拓展，例如 ext_random_pic.py 或者  ext_lolicon_pic.py 这些插件能否正常发送图片？根据你所提供的信息，目前只能怀疑可能是你使用的适配器不兼容这样的图片发送方式

**Comment by Elijah-0616** [comment]
> @Elijah-0616 hmm不是其它插件，而是其它的拓展，例如 ext_random_pic.py 或者  ext_lolicon_pic.py 这些插件能否正常发送图片？根据你所提供的信息，目前只能怀疑可能是你使用的适配器不兼容这样的图片发送方式

这个我明天试试，感谢大佬回复

**Comment by Elijah-0616** [comment]
> @Elijah-0616 hmm不是其它插件，而是其它的拓展，例如 ext_random_pic.py 或者 ext_lolicon_pic.py 这些插件能否正常发送图片？根据你所提供的信息，目前只能怀疑可能是你使用的适配器不兼容这样的图片发送方式

试过了ext_lolicon_pic，比较难触发，也许是我问得不对？但是能正常显示，不会显示编码

**Comment by KroMiose** [comment]
这个应该不是插件或者拓展本身的问题，或许需要排查gocq那边，你可以尝试在gocq那边寻找相关帮助https://github.com/Mrs4s/go-cqhttp/issues/2010

**Comment by Janet-Baker** [comment]
在 174d99f94b31cee8ca4b9f4a56e6d95d4ec51601 添加了默认超时时间5秒的设定。

改一下超时时间再编译，就可以发出来了。或者换一个快一点的服务器（

**Comment by KroMiose** [comment]
绘图过程是服务端即时进行的耗时操作，5秒时长大概率是不够用，建议先使用 [v1.0.0-rc4](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc4) 版本的gocq

**Comment by Janet-Baker** [comment]
可以试试我编译的这个，去掉了超时设定。

https://github.com/Janet-Baker/go-cqhttp/releases/tag/v1.0.0-rc5%2B20230328
